{
 "title": "health_dash",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GRPC Request Handling Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n   max(rate(grpc_server_handling_seconds_bucket{job=\"grpcserver\"}[1m])) by (le)\n)",
     "legendFormat": "grpc latency"
    }
   ]
  },
  {
   "title": "GRPC rps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "max(irate(grpc_server_started_total{grpc_method=\"PredictProba\", job=\"grpcserver\"}[5s]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (irate(process_cpu_seconds_total{job=\"grpcserver\"}[1m])) * 100)",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "PredictProba latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n   max(rate(probability_latency_bucket{job=\"grpcserver\", step=\"predict_proba\"}[1m])) by (le)\n)",
     "legendFormat": "q99 latency"
    }
   ]
  },
  {
   "title": "Total Number of Mallocs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(go_memstats_mallocs_total[1m]))",
     "legendFormat": "mallocs"
    }
   ]
  },
  {
   "title": "Garbage Collection durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "grpc latency" }
   ]
  }
 ]
}