// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package inferencer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	BannerId             uint64   `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	ZoneId               uint64   `protobuf:"varint,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Geo                  string   `protobuf:"bytes,3,opt,name=geo,proto3" json:"geo,omitempty"`
	Browser              uint64   `protobuf:"varint,4,opt,name=browser,proto3" json:"browser,omitempty"`
	OsVersion            string   `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Platform             uint64   `protobuf:"varint,6,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetBannerId() uint64 {
	if m != nil {
		return m.BannerId
	}
	return 0
}

func (m *Request) GetZoneId() uint64 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *Request) GetGeo() string {
	if m != nil {
		return m.Geo
	}
	return ""
}

func (m *Request) GetBrowser() uint64 {
	if m != nil {
		return m.Browser
	}
	return 0
}

func (m *Request) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *Request) GetPlatform() uint64 {
	if m != nil {
		return m.Platform
	}
	return 0
}

type Response struct {
	Proba                float64  `protobuf:"fixed64,1,opt,name=proba,proto3" json:"proba,omitempty"`
	Confidence           float64  `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProba() float64 {
	if m != nil {
		return m.Proba
	}
	return 0
}

func (m *Response) GetConfidence() float64 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "inferencer.Request")
	proto.RegisterType((*Response)(nil), "inferencer.Response")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3d, 0x4f, 0x03, 0x31,
	0x0c, 0x86, 0x15, 0xda, 0xde, 0x87, 0xc5, 0x80, 0x4c, 0x25, 0xa2, 0x22, 0x50, 0xd5, 0xa9, 0xd3,
	0x0d, 0x30, 0xb1, 0xb1, 0xa1, 0xdb, 0xaa, 0x0c, 0xac, 0xd5, 0x7d, 0xf8, 0x50, 0x24, 0x88, 0x83,
	0x73, 0x80, 0xc4, 0x0f, 0xe2, 0x77, 0xa2, 0x4b, 0x28, 0xd0, 0x2d, 0xcf, 0xe3, 0x58, 0xb6, 0x5f,
	0x28, 0x1b, 0x6f, 0x2b, 0x2f, 0x3c, 0x32, 0x82, 0x75, 0x03, 0x09, 0xb9, 0x8e, 0x64, 0xf3, 0xa5,
	0x20, 0x37, 0xf4, 0xfa, 0x46, 0x61, 0xc4, 0x4b, 0x28, 0xdb, 0xc6, 0x39, 0x92, 0xbd, 0xed, 0xb5,
	0x5a, 0xab, 0xed, 0xdc, 0x14, 0x49, 0xd4, 0x3d, 0x5e, 0x40, 0xfe, 0xc9, 0x8e, 0xa6, 0xd2, 0x49,
	0x2c, 0x65, 0x13, 0xd6, 0x3d, 0x9e, 0xc1, 0xec, 0x89, 0x58, 0xcf, 0xd6, 0x6a, 0x5b, 0x9a, 0xe9,
	0x89, 0x1a, 0xf2, 0x56, 0xf8, 0x23, 0x90, 0xe8, 0x79, 0xfc, 0x7a, 0x40, 0xbc, 0x02, 0xe0, 0xb0,
	0x7f, 0x27, 0x09, 0x96, 0x9d, 0x5e, 0xc4, 0x96, 0x92, 0xc3, 0x63, 0x12, 0xb8, 0x82, 0xc2, 0x3f,
	0x37, 0xe3, 0xc0, 0xf2, 0xa2, 0xb3, 0x34, 0xff, 0xc0, 0x9b, 0x7b, 0x28, 0x0c, 0x05, 0xcf, 0x2e,
	0x10, 0x2e, 0x61, 0xe1, 0x85, 0xdb, 0x26, 0x2e, 0xa9, 0x4c, 0x02, 0xbc, 0x06, 0xe8, 0xd8, 0x0d,
	0xb6, 0x9f, 0x2e, 0x8b, 0x4b, 0x2a, 0xf3, 0xcf, 0xdc, 0x3c, 0x00, 0xd4, 0xbf, 0x87, 0xe3, 0x1d,
	0x9c, 0xee, 0x84, 0x7a, 0xdb, 0x8d, 0xbb, 0xd8, 0x7d, 0x5e, 0xfd, 0xa5, 0x52, 0xfd, 0x24, 0xb2,
	0x5a, 0x1e, 0xcb, 0x34, 0xbe, 0xcd, 0x62, 0x8c, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x65,
	0x24, 0xd7, 0x8b, 0x53, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InferencerClient is the client API for Inferencer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InferencerClient interface {
	PredictProba(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type inferencerClient struct {
	cc *grpc.ClientConn
}

func NewInferencerClient(cc *grpc.ClientConn) InferencerClient {
	return &inferencerClient{cc}
}

func (c *inferencerClient) PredictProba(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/inferencer.Inferencer/PredictProba", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferencerServer is the server API for Inferencer service.
type InferencerServer interface {
	PredictProba(context.Context, *Request) (*Response, error)
}

// UnimplementedInferencerServer can be embedded to have forward compatible implementations.
type UnimplementedInferencerServer struct {
}

func (*UnimplementedInferencerServer) PredictProba(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictProba not implemented")
}

func RegisterInferencerServer(s *grpc.Server, srv InferencerServer) {
	s.RegisterService(&_Inferencer_serviceDesc, srv)
}

func _Inferencer_PredictProba_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferencerServer).PredictProba(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inferencer.Inferencer/PredictProba",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferencerServer).PredictProba(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inferencer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inferencer.Inferencer",
	HandlerType: (*InferencerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PredictProba",
			Handler:    _Inferencer_PredictProba_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
